### ISSUE TITLE
No versions tagged for okhttp

### ISSUE THREAD

**Issue by vanniktech** [joeyespo/github-version-tags#1]
OkHttp has some versions although they're not correctly shown:

<img width="1015" alt="screen shot 2018-02-23 at 14 22 23" src="https://user-images.githubusercontent.com/5759366/36596128-01339a34-18a5-11e8-8f9d-2236f1efaf3e.png">

[Link to Versions](https://github.com/square/okhttp/releases)

**Comment by joeyespo** [comment]
That's because these version numbers are prefixed with arbitrary text. The only tag schemes currently supported are raw semantic version numbers and those prefixed with a `v`.

Why? If *any* tag with a dotted number was allowed, you'd be more likely to see feature branches mistakenly showing up as version numbers.

The `v` prefix is sort of a community standard. If you can think of a way to allow other prefixes without much complexity or risk of mistaking feature branches for version numbers, feel free to make some suggestions here. Going to mark as "out of scope" for now.

Thanks for the issue!

(Oh, another idea is to open an issue with OkHttp and suggest using the more widely used tag scheme. Then this extension will work like it does in most other repos.)

**Comment by vanniktech** [comment]
I would not say it's arbitary text those `parent-` come from maven and I think we could also add that to the well known prefix - just as `v`
